version: "3"
services:
  consul:
    container_name: cert-manager.devstack.consul
    image: consul:1.2.2
    environment:
      CONSUL_BIND_INTERFACE: eth0
      PIPENV_VENV_IN_PROJECT: "true"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    tty: true
    ports:
      - "8500:8500"
  test:
    container_name:  cert-manager.devstack.test
    image: python:3.6
    environment:
      CONSUL_HTTP_ADDR: cert-manager.devstack.consul:8500
    volumes:
      - "$PWD:/opt/"
    tty: true
    command: ["/bin/bash"]
